### ISSUE TITLE
0.6+ Windows: auto update kills the app

### ISSUE THREAD

**Issue by metalaureate** [tari-project/universe#1049]
**Describe the bug**
On Windows, auto update kills the app. Does not relaunch the app or install any updates.

**Comment by Anziskavds** [comment]
This is also happening on a MacBook Air 13 inch M1 2020 on Testnet v0.6.4

**Comment by mmrrnn** [comment]
I've notice it's the case when upgrading from < v0.7.5 on windows. We run the app as an administrator from this version so it's just closed after auto-update.

I see this issue was created more than 2 weeks before that change, so I'll test it further on other systems

**Comment by mmrrnn** [comment]
Linux
---
works fine for:
* 0.7.4
* 0.7.0
* 0.6.17
* 0.6.14
* 0.6.6
* 0.6.2
* 0.6.1
* 0.6.0

**Comment by mmrrnn** [comment]
> Currently the updater fails for .app files on macOS if the file is not located in the "applications" folder. The error that is thrown is:
"Tauri API error: read-only filesystem error (os error 30)"
There is no feedback to the end-user as to what is going on.

Source: https://github.com/tauri-apps/tauri/issues/6282

The problem is when Tari Universe application is not moved to the Applications directory or executed copy that is not the same as one inside Applications directory(app is copied to the Application directory when "installing" the app so user can still run the copy without sufficient privileges)
