### ISSUE TITLE
Add JSON linter to CI for i18n files

### ISSUE THREAD

**Issue by stringhandler** [tari-project/universe#495]

**Comment by leet4tari** [comment]
JSon linter as part of the i18n CI is in place https://github.com/tari-project/universe/pull/498

**Comment by leet4tari** [comment]
Ran into an issue where there was no standard JSon linter for Linux/OSX (did not check on Windows). 

Command lines and switches are not the same between tools. Might be an idea to  use ```jq``` to validate all JSon files with some usage notes, so that JSon files can be validated locally without a push into repo.
