### ISSUE TITLE
Uninstalling the Tari Universe app on Mac does not remove associated files

### ISSUE THREAD

**Issue by ghost** [tari-project/universe#88]
**Creating this bug ticket as a record of Mac behavior. There may be a story to address this flow.**
When the app is uninstalled on Mac, the following files are still found:
1. ~/Library/Caches/com.tari.universe
2. ~/Library/Logs/com.tari.universe
3. ~/Library/Applicaton Support/com.tari.universe

**To Reproduce**
1. Uninstall the Tari Universe app by moving it to trash
2. search ~/Library/Caches/com.tari.universe
3. search ~/Library/Logs/com.tari.universe
4. search ~/Library/Applicaton Support/com.tari.universe

**Expected behavior**
After a discussion with Mike and Simon, we determined Mac does not delete associated files when apps are deleted. A suggestion to alter the uninstall flow with something like "a previous installation was detected do you want to use it?" in case a user uninstalls to fix an issue. A final decision on how to handle this will be considered. 

**Desktop (please complete the following information):**
 - OS & Version: Mac M1 Sonoma 14.6.1

**Comment by mmrrnn** [comment]
macOS
---
On macOS, there isn't a classic uninstallation step for `.dmg` bundles.

Linux
---
`AppImages` are standalone executables, and there is no formal installation or uninstallation process. Users simply delete the file, which means we cannot automate the cleanup of related files.

Windows
---
The WiX toolset potentially provides custom actions during uninstallation, and we probably can modify Tauri's default template to include them. However, since the application is already removed when the uninstall process runs, executing JavaScript commands or accessing the application's context won't be possible. We need to remember that Tauri supports only WiX v3 which is quite tricky

@stringhandler
