### ISSUE TITLE
Start client after auto-update while mac screen locked

### ISSUE THREAD

**Issue by palomato** [tari-project/universe#988]
When the mac screen locks with auto-updates enabled, the client does not automatically start running again after an update until the screen is unlocked.

I leave the mac running/mining and check on it every few days, so it can be days of missed mining time when the client doesn't automatically resume mining after an update.

Mac OS 15

**Comment by brianp** [comment]
That's a very interesting use case. I'm not sure we can do anything about it if the OS is stalling the start because the system is locked. We will investigate.

In the mean time a workaround for you would be to turn off auto-update. It will then require you to confirm with a dialog to perform the update, and you won't have missed any mining time.

**Comment by palomato** [comment]
The last two updates (currently on 0.7.7) the client completes the auto-update and relaunches on its own. As such, I believe this issue to be resolved.
